# Generated by Django 5.2.4 on 2025-07-14 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory_inventory', '0004_alter_materialincoming_notes'),
        ('operations_workshops', '0001_initial'),
        ('services', '0004_remove_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('door', 'Дверь')], default='door', max_length=50, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('services', models.ManyToManyField(related_name='products', to='services.service', verbose_name='Услуги для продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Расход на единицу продукции')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_inventory.rawmaterial', verbose_name='Сырьё')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations_workshops.workshop', verbose_name='Цех')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Норма расхода сырья',
                'verbose_name_plural': 'Нормы расхода сырья',
                'unique_together': {('product', 'workshop', 'material')},
            },
        ),
    ]
