# Generated by Django 5.2 on 2025-08-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img_product_is_glass'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='glass_type',
            field=models.CharField(blank=True, choices=[('sandblasted', 'Пескоструйный'), ('uv', 'УФ')], help_text='Указывается только для стеклянных изделий', max_length=20, null=True, verbose_name='Тип стекла'),
        ),
    ]
