# Generated by Django 5.2.4 on 2025-09-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_glass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_3_floor',
            field=models.BooleanField(default=False, help_text='Если True, то после цеха 8 заявка идет в цех 13, а этапы 9-12 выполняются автоматически', verbose_name='3-й этаж'),
        ),
    ]
