# Generated by Django 5.2.4 on 2025-07-14 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_workshops', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='OrderDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество брака')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_defects', to='orders.order')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations_workshops.workshop')),
            ],
            options={
                'verbose_name': 'Брак по заказу',
                'verbose_name_plural': 'Браки по заказу',
            },
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.PositiveIntegerField(default=0, verbose_name='В работе')),
                ('defective', models.PositiveIntegerField(default=0, verbose_name='Брак')),
                ('completed', models.PositiveIntegerField(default=0, verbose_name='Передано дальше')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.order')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations_workshops.workshop')),
            ],
            options={
                'verbose_name': 'Этап заказа',
                'verbose_name_plural': 'Этапы заказа',
                'unique_together': {('order', 'workshop')},
            },
        ),
    ]
