# Generated by Django 5.2.4 on 2025-07-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0001_initial'),
        ('operations_workshops', '0001_initial'),
        ('orders', '0002_alter_order_comment_orderdefect_orderstage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderstage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='finished_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finished_goods.finishedgood'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='stage_type',
            field=models.CharField(choices=[('workshop', 'Цех'), ('stock', 'Склад готовой продукции')], default='workshop', max_length=20, verbose_name='Тип этапа'),
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_workshops.workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstage',
            unique_together={('order', 'workshop', 'stage_type', 'finished_good')},
        ),
    ]
