# Generated by Django 5.2.4 on 2025-07-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderstage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('production', 'В производстве'), ('stock', 'На складе'), ('shipped', 'Отправлен клиенту')], default='production', max_length=30, verbose_name='Статус'),
        ),
    ]
