# Generated by Django 5.2 on 2025-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstage',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполнено (кол-во)'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='operation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='plan_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='План (кол-во)'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередность'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('done', 'Завершено'), ('partial', 'Частично завершено'), ('waiting', 'Ожидание')], default='in_progress', max_length=30, verbose_name='Статус'),
        ),
    ]
