# Generated by Django 5.2.4 on 2025-07-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstage_completed_quantity_orderstage_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('production', 'В производстве'), ('stock', 'На складе'), ('shipped', 'Отправлен клиенту'), ('new', 'Новая')], default='production', max_length=30, verbose_name='Статус'),
        ),
    ]
