# Generated by Django 5.2.4 on 2025-08-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0005_employeetask_earnings_employeetask_net_earnings_and_more'),
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdefect',
            options={'ordering': ['-date'], 'verbose_name': 'Брак по заказу', 'verbose_name_plural': 'Браки по заказу'},
        ),
        migrations.AddField(
            model_name='orderdefect',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий админа'),
        ),
        migrations.AddField(
            model_name='orderdefect',
            name='rework_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость переработки'),
        ),
        migrations.AddField(
            model_name='orderdefect',
            name='rework_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок переработки'),
        ),
        migrations.AddField(
            model_name='orderdefect',
            name='rework_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reworked_defects', to='employee_tasks.employeetask'),
        ),
        migrations.AddField(
            model_name='orderdefect',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Ожидает проверки'), ('approved_for_rework', 'Разрешена переработка'), ('in_rework', 'В переработке'), ('reworked', 'Переработан'), ('rejected', 'Отклонен')], default='pending_review', max_length=30, verbose_name='Статус брака'),
        ),
    ]
