# Generated by Django 5.2 on 2025-08-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0002_finishedgood_order_item_finishedgood_packaging_date_and_more'),
        ('operations_workshops', '0001_initial'),
        ('orders', '0008_alter_order_product_orderitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderstage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cnc_specs',
            field=models.TextField(blank=True, verbose_name='Спецификации для ЧПУ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cutting_specs',
            field=models.TextField(blank=True, verbose_name='Спецификации для распила'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='glass_cutting_completed',
            field=models.BooleanField(default=False, verbose_name='Резка стекла завершена'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='glass_cutting_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество порезанного стекла'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='glass_type',
            field=models.CharField(blank=True, help_text='Пескоструйный или УФ', max_length=20, verbose_name='Тип стекла'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging_notes',
            field=models.TextField(blank=True, verbose_name='Заметки для упаковки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging_received_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество полученное в упаковке'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paint_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет краски'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paint_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип краски'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.orderitem', verbose_name='Позиция заказа'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='parallel_group',
            field=models.PositiveIntegerField(blank=True, help_text='Для параллельных потоков (например, стекло)', null=True, verbose_name='Группа параллельной обработки'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstage',
            unique_together={('order', 'workshop', 'stage_type', 'finished_good', 'order_item', 'parallel_group')},
        ),
    ]
