# Generated by Django 5.2 on 2025-08-22 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderstage_unique_together_orderitem_cnc_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstage',
            name='cnc_specs',
            field=models.TextField(blank=True, null=True, verbose_name='Спецификации ЧПУ'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstage',
            name='cutting_specs',
            field=models.TextField(blank=True, null=True, verbose_name='Спецификации распила'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='paint_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет краски'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='paint_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип краски'),
        ),
        migrations.AddField(
            model_name='orderstage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
