# Generated by Django 5.2.4 on 2025-09-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderstage_cnc_specs_orderstage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preparation_specs',
            field=models.TextField(blank=True, help_text='Комментарии и спецификации для цеха заготовки (ID 4)', verbose_name='Спецификации для цеха заготовки'),
        ),
    ]
