# Generated by Django 5.2.4 on 2025-07-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0004_alter_materialincoming_notes'),
        ('operations_workshops', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
        migrations.AddField(
            model_name='service',
            name='defect_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Штраф за брак'),
        ),
        migrations.AddField(
            model_name='service',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Траты сырья'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплата за услугу'),
        ),
        migrations.AddField(
            model_name='service',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_workshops.workshop', verbose_name='Цех'),
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Расход сырья на услугу')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_materials', to='factory_inventory.rawmaterial')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_materials', to='services.service')),
            ],
            options={
                'verbose_name': 'Сырьё для услуги',
                'verbose_name_plural': 'Сырьё для услуги',
                'unique_together': {('service', 'material')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='materials',
            field=models.ManyToManyField(related_name='services', through='services.ServiceMaterial', to='factory_inventory.rawmaterial', verbose_name='Список сырья'),
        ),
    ]
