# Generated by Django 5.2.4 on 2025-07-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_code_service_defect_penalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='material_cost',
        ),
    ]
