# Generated by Django 4.2.7 on 2024-01-01 12:00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.expensecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('bank_details', models.TextField(blank=True, verbose_name='Банковские реквизиты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс (сом)')),
                ('currency', models.CharField(default='KGS', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Основной банковский счет',
                'verbose_name_plural': 'Основной банковский счет',
            },
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара/услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за единицу (сом)')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('purchase_frequency', models.IntegerField(default=30, verbose_name='Частота покупок (дней)')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата последней покупки')),
                ('next_purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей покупки')),
                ('warehouse_connection', models.CharField(blank=True, max_length=200, verbose_name='Связь со складом')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщиков',
                'ordering': ['supplier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('deposit', 'Вложение'), ('withdrawal', 'Инкассация')], max_length=20, verbose_name='Тип движения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма (сом)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Движение денег',
                'verbose_name_plural': 'Движение денег',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма (сом)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счета')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensecategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('sales', 'С продаж'), ('other', 'Другое')], max_length=20, verbose_name='Тип дохода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма (сом)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order_reference', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на заказ')),
                ('date', models.DateField(verbose_name='Дата дохода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FactoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('asset_type', models.CharField(choices=[('building', 'Здание'), ('equipment', 'Оборудование'), ('vehicle', 'Транспорт'), ('furniture', 'Мебель'), ('electronics', 'Электроника'), ('other', 'Другое')], max_length=20, verbose_name='Тип имущества')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена покупки (сом)')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Текущая стоимость (сом)')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Имущество завода',
                'verbose_name_plural': 'Имущество завода',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Месячный'), ('quarterly', 'Квартальный'), ('yearly', 'Годовой'), ('custom', 'Произвольный')], max_length=20, verbose_name='Тип отчета')),
                ('title', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общий доход')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общий расход')),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Чистый доход')),
                ('operating_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Операционный доход')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая стоимость активов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Финансовый отчет',
                'verbose_name_plural': 'Финансовые отчеты',
                'ordering': ['-created_at'],
            },
        ),
    ] 