# Generated by Django 5.2.4 on 2025-08-19 15:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_supplier_category_supplier_code_supplier_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('payable', 'Мы должны (поставщикам)'), ('receivable', 'Нам должны (клиенты)')], max_length=20, verbose_name='Направление')),
                ('counterparty_name', models.CharField(blank=True, max_length=200, verbose_name='Контрагент (если не поставщик)')),
                ('title', models.CharField(max_length=200, verbose_name='Назначение долга')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма долга')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Оплачено')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма оплаты')),
                ('date', models.DateField(verbose_name='Дата оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.debt', verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Оплата долга',
                'verbose_name_plural': 'Оплаты долгов',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
