# Generated by Django 5.2.4 on 2025-08-28 03:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_debt_debtpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код счета')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование счета')),
                ('account_type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Пассив'), ('equity', 'Капитал'), ('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип (Актив/Пассив/…)')),
                ('normal_side', models.CharField(choices=[('debit', 'Дебет'), ('credit', 'Кредит')], max_length=6, verbose_name='Нормальная сторона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.accountingaccount', verbose_name='Родительский счет')),
            ],
            options={
                'verbose_name': 'Счет учета',
                'verbose_name_plural': 'План счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted', models.BooleanField(default=True, verbose_name='Проведено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Журнал операции',
                'verbose_name_plural': 'Журнал операций',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Кредит')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.accountingaccount', verbose_name='Счет')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Строка проводки',
                'verbose_name_plural': 'Строки проводок',
            },
        ),
    ]
