# Generated by Django 5.2.4 on 2025-08-29 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accountingaccount_journalentry_journalentryline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код аналитического счета')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_accounts', to='finance.accountingaccount', verbose_name='Синтетический счет')),
            ],
            options={
                'verbose_name': 'Аналитический счет',
                'verbose_name_plural': 'Аналитические счета',
                'ordering': ['parent_account', 'code'],
                'unique_together': {('parent_account', 'code')},
            },
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='analytical_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.analyticalaccount', verbose_name='Аналитический счет'),
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название периода')),
                ('period_type', models.CharField(choices=[('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], max_length=20, verbose_name='Тип периода')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
            ],
            options={
                'verbose_name': 'Финансовый период',
                'verbose_name_plural': 'Финансовые периоды',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StandardOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Типовая операция',
                'verbose_name_plural': 'Типовые операции',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandardOperationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('debit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент по дебету')),
                ('credit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент по кредиту')),
                ('is_variable', models.BooleanField(default=False, verbose_name='Переменная сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.accountingaccount', verbose_name='Счет')),
                ('analytical_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.analyticalaccount', verbose_name='Аналитический счет')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.standardoperation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Строка типовой операции',
                'verbose_name_plural': 'Строки типовых операций',
            },
        ),
        migrations.CreateModel(
            name='AccountCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание корреспонденции')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Корректна')),
                ('warning_message', models.TextField(blank=True, verbose_name='Предупреждение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_correspondences', to='finance.accountingaccount', verbose_name='Счет по кредиту')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_correspondences', to='finance.accountingaccount', verbose_name='Счет по дебету')),
            ],
            options={
                'verbose_name': 'Корреспонденция счетов',
                'verbose_name_plural': 'Корреспонденции счетов',
                'ordering': ['debit_account', 'credit_account'],
                'unique_together': {('debit_account', 'credit_account')},
            },
        ),
    ]
