# Generated by Django 5.2.4 on 2025-08-30 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_status'),
        ('finance', '0005_analyticalaccount_and_more'),
        ('operations_workshops', '0002_alter_workshop_manager_workshopmaster'),
        ('orders', '0010_orderstage_cnc_specs_orderstage_created_at_and_more'),
        ('products', '0003_product_glass_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('assigned', 'Назначена на цех')], default='pending', max_length=30, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата назначения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('assigned_to_workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='operations_workshops.workshop', verbose_name='Назначен на цех')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='orders.order', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('glass_type', models.CharField(blank=True, help_text='Пескоструйный или УФ', max_length=20, verbose_name='Тип стекла')),
                ('paint_type', models.CharField(blank=True, max_length=100, verbose_name='Тип краски')),
                ('paint_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет краски')),
                ('cnc_specs', models.TextField(blank=True, verbose_name='Спецификации для ЧПУ')),
                ('cutting_specs', models.TextField(blank=True, verbose_name='Спецификации для распила')),
                ('packaging_notes', models.TextField(blank=True, verbose_name='Заметки для упаковки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='products.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
            },
        ),
    ]
