# Generated by Django 5.2.4 on 2025-08-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_request_requestitem'),
        ('orders', '0010_orderstage_cnc_specs_orderstage_created_at_and_more'),
        ('products', '0003_product_glass_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestitem',
            options={'verbose_name': 'Элемент заявки', 'verbose_name_plural': 'Элементы заявки'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='admin_comment',
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата назначения на цех'),
        ),
        migrations.AlterField(
            model_name='request',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('assigned', 'Назначена на цех')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='glass_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип стекла'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
    ]
