# Generated by Django 5.2.4 on 2025-08-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_requestitem_options_and_more'),
        ('orders', '0010_orderstage_cnc_specs_orderstage_created_at_and_more'),
        ('products', '0003_product_glass_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestitem',
            options={'verbose_name': 'Позиция заявки', 'verbose_name_plural': 'Позиции заявки'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='assigned_to_workshop',
        ),
        migrations.RemoveField(
            model_name='request',
            name='created_by',
        ),
        migrations.AddField(
            model_name='request',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='request',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='orders.order', verbose_name='Связанный заказ'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('in_production', 'В производстве')], default='pending', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='glass_type',
            field=models.CharField(blank=True, help_text='Пескоструйный или УФ', max_length=20, verbose_name='Тип стекла'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='products.product', verbose_name='Товар'),
        ),
    ]
