# Generated by Django 5.2.4 on 2025-09-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_requestitem_options_remove_request_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='preparation_specs',
            field=models.TextField(blank=True, help_text='Комментарии и спецификации для цеха заготовки (ID 4)', verbose_name='Спецификации для цеха заготовки'),
        ),
    ]
