# Generated by Django 5.2.4 on 2025-08-14 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations_workshops', '0001_initial'),
        ('products', '0002_product_img_product_is_glass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(blank=True, choices=[('technical', 'Технический'), ('manual', 'Ручной')], max_length=20, null=True, verbose_name='Тип брака')),
                ('status', models.CharField(choices=[('pending_master_review', 'Ожидает проверки мастера'), ('master_confirmed', 'Подтвержден мастером'), ('can_be_fixed', 'Можно починить'), ('sent_to_workshop', 'Отправлен в цех для починки'), ('fixed', 'Починен'), ('unrepairable', 'Не подлежит починке')], default='pending_master_review', max_length=30, verbose_name='Статус брака')),
                ('master_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения мастером')),
                ('can_be_fixed', models.BooleanField(blank=True, null=True, verbose_name='Можно починить')),
                ('repair_task_created', models.BooleanField(default=False, verbose_name='Задача на починку создана')),
                ('penalty_applied', models.BooleanField(default=False, verbose_name='Штраф применен')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа')),
                ('master_comment', models.TextField(blank=True, verbose_name='Комментарий мастера')),
                ('repair_comment', models.TextField(blank=True, verbose_name='Комментарий по починке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата брака')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('master_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_defects', to=settings.AUTH_USER_MODEL, verbose_name='Мастер подтвердивший брак')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.product', verbose_name='Продукт')),
                ('target_workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_defects', to='operations_workshops.workshop', verbose_name='Цех для починки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (кто создал брак)')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='operations_workshops.workshop', verbose_name='Цех где произошел брак')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Браки',
                'ordering': ['-created_at'],
            },
        ),
    ]
