# Generated by Django 5.2.4 on 2025-07-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='description',
        ),
    ]
