# Generated by Django 5.2.4 on 2025-08-13 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_remove_defect_description'),
        ('operations_workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={'ordering': ['-created_at'], 'verbose_name': 'Брак', 'verbose_name_plural': 'Браки'},
        ),
        migrations.AddField(
            model_name='defect',
            name='can_be_fixed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Можно ли починить'),
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_type',
            field=models.CharField(blank=True, choices=[('technical', 'Технический'), ('manual', 'Ручной')], max_length=20, null=True, verbose_name='Тип брака'),
        ),
        migrations.AddField(
            model_name='defect',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исправления'),
        ),
        migrations.AddField(
            model_name='defect',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_defects', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, исправивший брак'),
        ),
        migrations.AddField(
            model_name='defect',
            name='master_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения мастером'),
        ),
        migrations.AddField(
            model_name='defect',
            name='master_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_defects', to=settings.AUTH_USER_MODEL, verbose_name='Мастер, подтвердивший брак'),
        ),
        migrations.AddField(
            model_name='defect',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('pending_master_review', 'Ожидает проверки мастера'), ('master_confirmed', 'Подтвержден мастером'), ('can_be_fixed', 'Можно починить'), ('sent_to_workshop', 'Отправлен в цех для восстановления'), ('fixed', 'Исправлен'), ('unrepairable', 'Не подлежит восстановлению')], default='pending_master_review', max_length=30, verbose_name='Статус брака'),
        ),
        migrations.AddField(
            model_name='defect',
            name='target_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_to_fix', to='operations_workshops.workshop', verbose_name='Цех для восстановления'),
        ),
        migrations.CreateModel(
            name='DefectRepairTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выполнения'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус задачи')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка времени (часы)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Фактическое время (часы)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_repair_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначено на')),
                ('defect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair_task', to='defects.defect', verbose_name='Брак')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_repair_tasks', to='operations_workshops.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Задача по восстановлению брака',
                'verbose_name_plural': 'Задачи по восстановлению браков',
                'ordering': ['-created_at'],
            },
        ),
    ]
