# Generated by Django 5.2.4 on 2025-08-22 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_add_employee_task_relation'),
        ('products', '0003_product_glass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.product', verbose_name='Продукт'),
        ),
    ]
