# Generated by Django 5.2.4 on 2025-08-25 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_alter_defect_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_defects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подтвердивший брак'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='master_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий подтверждающего'),
        ),
    ]
