# Generated by Django 5.2.4 on 2025-07-14 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_comment_orderdefect_orderstage'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('status', models.CharField(choices=[('stock', 'На складе'), ('issued', 'Выдано')], default='stock', max_length=20, verbose_name='Статус')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Получатель')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_goods', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция (склад)',
                'ordering': ['-received_at'],
            },
        ),
    ]
