# Generated by Django 5.2 on 2025-08-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0001_initial'),
        ('operations_workshops', '0001_initial'),
        ('orders', '0008_alter_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_goods', to='orders.orderitem', verbose_name='Позиция заказа'),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='packaging_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата упаковки'),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='quality_check_passed',
            field=models.BooleanField(default=False, verbose_name='Проверка качества пройдена'),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_workshops.workshop', verbose_name='Цех производства'),
        ),
        migrations.AlterField(
            model_name='finishedgood',
            name='status',
            field=models.CharField(choices=[('stock', 'На складе'), ('issued', 'Выдано'), ('reserved', 'Зарезервировано')], default='stock', max_length=20, verbose_name='Статус'),
        ),
    ]
