# Generated by Django 5.2.4 on 2025-07-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_workshops', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='operations_workshops.workshop', verbose_name='Цех'),
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
