# Generated by Django 5.2.4 on 2025-08-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_full_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('founder', 'Учредитель'), ('director', 'Директор'), ('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('master', 'Мастер (руководитель цеха)'), ('worker', 'Рабочий'), ('helper', 'Помощник')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
