# Generated by Django 5.2.4 on 2025-08-28 03:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Текущий баланс пользователя в сомах', max_digits=12, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('founder', 'Учредитель'), ('director', 'Директор'), ('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('master', 'Мастер (руководитель цеха)'), ('worker', 'Рабочий')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
