# Generated by Django 5.2.4 on 2025-07-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Артикул/Код')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Мин. остаток')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сырье/материал',
                'verbose_name_plural': 'Сырье и материалы',
                'ordering': ['name'],
            },
        ),
    ]
