# Generated by Django 5.2.4 on 2025-07-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер'),
        ),
    ]
