# Generated by Django 5.2.4 on 2025-07-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0002_rawmaterial_price_rawmaterial_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество прихода')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за единицу')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общая стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomings', to='factory_inventory.rawmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Приход материала',
                'verbose_name_plural': 'Приходы материалов',
                'ordering': ['-created_at'],
            },
        ),
    ]
