# Generated by Django 5.2.4 on 2025-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0003_materialincoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialincoming',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
