# Generated by Django 5.2.4 on 2025-08-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0004_alter_materialincoming_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул/Код'),
        ),
    ]
