# Generated by Django 5.2.4 on 2025-08-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0005_employeetask_earnings_employeetask_net_earnings_and_more'),
        ('factory_inventory', '0005_alter_rawmaterial_code_auto_generate'),
        ('operations_workshops', '0001_initial'),
        ('orders', '0007_alter_orderdefect_options_orderdefect_admin_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество израсходовано')),
                ('consumed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расхода')),
                ('employee_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='employee_tasks.employeetask')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='factory_inventory.rawmaterial')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_consumptions', to='operations_workshops.workshop')),
            ],
            options={
                'verbose_name': 'Расход сырья',
                'verbose_name_plural': 'Расходы сырья',
                'ordering': ['-consumed_at'],
            },
        ),
    ]
