# Generated by Django 5.2 on 2025-07-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
