# Generated by Django 5.2 on 2025-07-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0002_employeetask_completed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='defective_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
