# Generated by Django 5.2.4 on 2025-07-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0003_employeetask_defective_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetask',
            options={'verbose_name': 'Задача сотрудника', 'verbose_name_plural': 'Задачи сотрудников'},
        ),
        migrations.AddField(
            model_name='employeetask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
