# Generated by Django 5.2.4 on 2025-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0004_alter_employeetask_options_employeetask_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Заработок'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='net_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистый заработок'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='penalties',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штрафы'),
        ),
    ]
