# Generated by Django 5.2.4 on 2025-08-24 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0005_employeetask_earnings_employeetask_net_earnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('completed_quantity', models.PositiveIntegerField(default=0)),
                ('defective_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Заработок')),
                ('penalties', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штрафы')),
                ('net_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистый заработок')),
                ('employee_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_tasks', to='employee_tasks.employeetask')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача помощника',
                'verbose_name_plural': 'Задачи помощников',
                'unique_together': {('employee_task', 'helper')},
            },
        ),
    ]
