# Generated by Django 5.2.4 on 2025-08-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0006_helpertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpertask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='helpertask',
            name='completed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='helpertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='helpertask',
            name='defective_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Брак'),
        ),
        migrations.AlterField(
            model_name='helpertask',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество для помощи'),
        ),
    ]
