# Generated by Django 5.2.4 on 2025-08-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0007_alter_helpertask_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='additional_penalties',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дополнительные штрафы'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='custom_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Индивидуальная цена за единицу'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='layers_per_unit',
            field=models.PositiveIntegerField(default=1, verbose_name='Слоёв на единицу'),
        ),
        migrations.DeleteModel(
            name='HelperTask',
        ),
    ]
