# Generated by Django 5.2.4 on 2025-08-24 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_managed_workshops', to=settings.AUTH_USER_MODEL, verbose_name='Главный руководитель (мастер)'),
        ),
        migrations.CreateModel(
            name='WorkshopMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_workshop_masters', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_master_roles', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_masters', to='operations_workshops.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Мастер цеха',
                'verbose_name_plural': 'Мастера цехов',
                'ordering': ['-added_at'],
                'unique_together': {('workshop', 'master')},
            },
        ),
    ]
