# Generated by Django 5.2 on 2025-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('potential', 'Потенциальный'), ('blocked', 'Заблокирован')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
